language: groovy
jdk:
  - openjdk8
sudo: false
branches:
  only:
    - master
    - develop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker-compose -f elastic.yml up -d

after_success:
  - 'export GRADLE_OPTS="-Dgrails.env=travis"'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish --stacktrace --debug'

after_script:
  - docker-compose -f elastic.yml kill

after_failure:
  - cat /home/travis/build/AtlasOfLivingAustralia/image-service/build/test-results/integrationTest/*

env:
  global:
  - secure: rWlywM7xq6UpiQJKSmfXM/lEURpBBtczVabWTFsL2APFu/ZkqeN8WTlLvvyupi6B4MXBUCpXkVQyGSdsoxUNrAQ6+HI7vYuCI0C44j+SelkoMgLjxsfWvRmc4FnP924LX3c9KqAjkjuMZ/cfUjomEuWiUiMCvwJO5laCCE9+Do4=
  - secure: L2tXyQ3jVEDAOnhTUWJR8mzXXRp9VLAmlybS9gNy9cnsSdegLFZk/P8Og+AjY+X54sHGc7KOipMs5cJmNE9XG5IDCKq0m7LFNog6goI8N4/xi95k6vNXyeoIlcASpCAMW0YqLyZNz+oGbmmdhIwz8xdSZTPnrZWHPyczYkbb++0=
